# Generated by Django 3.1.2 on 2020-10-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='subsribed',
            field=models.IntegerField(default=0),
        ),
    ]
