# Generated by Django 3.1.2 on 2020-10-21 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201020_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='subscribed',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 10, 53, 13, 598028)),
        ),
    ]
